from turtle import Turtle

class Border(Turtle):
    def __init__(self):
        super().__init__()
        self.color("white")
        self.left(90)
        self.penup()
        self.forward(275)
        self.pendown()
        self.right(90)
        self.forward(320)
        self.right(90)
        self.penup()
        self.forward(550)
        self.right(90)
        self.pendown()
        self.forward(620)
        self.penup()
        self.right(90)
        self.forward(550)
        self.pendown()
        self.right(90)
        self.forward(300)
        self.penup()
        self.setheading(270)
        self.forward(500)
        self.setheading(0)
        self.forward(320)
        self.pendown()
        self.setheading(180)
        self.forward(620)
        self.hideturtle()